##### Load the files which have been saved in the working directory

source("SPM_Ini.R")
source("SPM_A_Posteriori.R")
source("SPM_Trial.R")



############################# The context:
#### sizeD is the number of doses, D is the range of doses, 
#### alpha is the target in term of probability of toxicity, 
#### T is the scenario generated by the pseudo uniform algorithm,
#### sizeT is the number of patient in the Trial,
sizeD=8
D=1:sizeD
alpha=0.25
sizeTr=25


mtd<-sample(D,1,replace=TRUE,prob=rep(1/length(D),sizeD))
if(mtd<sizeD){temp<-sort(runif(length(D)-mtd,alpha,1));bornesup<-temp[length(D)-mtd]}
if(mtd==sizeD){bornesup<-alpha +(1-alpha)*rbeta(1,0.5,1)}
test<-0
while(test==0){T<-sort(runif(sizeD,0,bornesup))
               temp<-which.min(abs(T-alpha))
               if(temp==mtd){test<-1}
              }
print(T)

############################# Observations during the trial
#### Seq_Obs is the sequence of observations, 
#### Seq_Obs[1,j]= X_j, Seq_Obs[2,j]=Y_j (1:tox ; 0:non-tox)
#### Sum_Obs is the summarize of Seq_obs
#### Sum_Obs[1,j]= number of tox observed at dose j
#### Sum_Obs[2,j]= number of non-tox observed at dose j
Sum_Obs<-matrix(rep(0, 2*sizeD),2,sizeD)
Seq_Obs<-matrix(rep(0, 2*sizeTr),2,sizeTr)

############################# The prior model is described by the Equation 7 section 2.2
#### mat_prior_model is the matrice of the elements q_\theta^j with 
#### mat_prior_model[,\theta]= (q_\theta^1, ... , q_\theta^j)
#### c is the number of pseudo subject observed, epsilon is the size of the centered interval on alpha,
#### Vec_norm, is a vector for normalizing the prior model (technical tool) which should be evaluated for ech new prior model.  
#### one example, run:
mat_prior_model<-matrix(rep(0,sizeD*sizeD),sizeD,sizeD)
for(i in D)
{
  for(j in D)
  {
    if(j<(i-1)){mat_prior_model[j,i]<-0.4*alpha}
    if(j==(i-1)){mat_prior_model[j,i]<-0.6*alpha}
    if(j>(i+1)){mat_prior_model[j,i]<-1.6*alpha}
    if(j==(i+1)){mat_prior_model[j,i]<-1.4*alpha}
  }
  mat_prior_model[i,i]<-alpha
}

c=40 ; epsilon=0 ;Vec_norm<-Ini(mat_prior_model,c,epsilon)

############################# Possible calibration for Pi
#### Normalized vector not needed (Proportionnality)
#First Example
Pi<-c(1,1,1,1,1,1)
#Second Example
Pi<-c(1,0.9428,0.9428^2*0.9556601,0.9428^3*0.9556601^2,0.9428^4*0.9556601^3,0.9428^5*0.9556601^4)

############################ A posteriori Pi_n according to sum_obs
####Pi_n[i]: probability of being the MTD for dose i according to the observations 
Pi_n=A_Posteriori(Sum_Obs, mat_prior_model, c, Vec_norm, Pi, epsilon)

#### Histogramme of Pi_n
#Names<-'1';for(i in D[2:sizeD]){Names<-c(Names,i)};names(Pi_n)=Names
#barplot(Pi_n, col = "lightblue", border = "blue",ylim=c(0,0.5),names.arg = toupper(names(Pi_n)), cex.names = 1, cex.axis = 0.8, xlab = "Doses", ylab = "Probability", axes = TRUE)

########################### Generate a trial under the scenario T
#### Different options are useful to simulate under the same condition than a real trial:
#### Cohort, number of patient that we allocate at a same dose;
#### skip, if skip=1 the method is allowed to skip a dose  (the other case corresponds to skip=0) 
#### caution, minimal number of patient treated at dose j before to allocate a patient at a dose above for the first time
#### dose_exclusion, if dose_exclusion=0 we do not exclude any dose or stop the trial early,
#### if dose_exclusion=p>0 we exclude all the dose such that P(DLT at dose j|data)>p.

#### The function trial return a list with the following elements:
#### $Observations$Sum_Obs: Sum_Obs at the end of the trial
#### $Observations$Seq_Obs: Seq_Obs at the end of the trial
#### $Pi_n: final a posteriori 
#### $mtd: recommended mtd (argument maximum of Pi_n)
#### $nbrpat: Number of patient treated
#### $matPi_n: all the sequence of a posteriori; matPi_n[i,] is the a posteriori after the i-th patient

#First example: Pi is unform, we do not allow the method to skip a dose
cohort=1;skip=0;caution=1;dose_exclusion=0;Pi<-rep(1,sizeD)
result<-Trial(sizeTr,T,c,mat_prior_model,Vec_norm, Pi,epsilon,cohort,skip,caution,dose_exclusion)
result

#Second example: Pi is decreasing, the method does not skip any doses naturally
Pi[1]=1;Pi[2]=0.9428;for(i in 3:sizeD){Pi[i]=(0.9428^(i-1))*(0.9556601^(i-2))}
cohort=1;skip=1;caution=1;dose_exclusion=0
result<-Trial(sizeTr,T,c,mat_prior_model,Vec_norm, Pi,epsilon,cohort,skip,caution,dose_exclusion)
result


#### A posteriori along the trial, to wathch in regard of result$Observations$Seq_Obs
Pi_n=Pi/sum(Pi)
Names<-'1';for(i in D[2:sizeD]){Names<-c(Names,i)};names(Pi_n)=Names
barplot(Pi_n, main="Probabilities a priori",col = "lightblue", border = "blue",ylim=c(0,0.5),names.arg = toupper(names(Pi_n)), cex.names = 1, cex.axis = 0.8, xlab = "Doses", ylab = "Probability", axes = TRUE)
for(k in 1:sizeTr){
  Pi_n=result$matPi_n[k,]
Names<-'1';for(i in D[2:sizeD]){Names<-c(Names,i)};names(Pi_n)=Names
barplot(Pi_n, main=paste("Probabilities a posteriori after the ",k,"th patient",sep=""),col = "lightblue", border = "blue",ylim=c(0,0.5),names.arg = toupper(names(Pi_n)), cex.names = 1, cex.axis = 0.8, xlab = "Doses", ylab = "Probability", axes = TRUE)
}

result$Observations$Seq_Obs
T
